binde = $mainMod+Alt, equal, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.1')
binde = $mainMod+Alt, minus, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.9) | if . < 1 then 1 else . end')
binde = $mainMod+Alt, KP_ADD, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.1')
binde = $mainMod+Alt, KP_SUBTRACT, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.9) | if . < 1 then 1 else . end')


# Move between grouped windows
bind = $mainMod CTRL , H, changegroupactive, b
bind = $mainMod CTRL , L, changegroupactive, f

# Resize windows
binde = $mainMod+Shift, Right, resizeactive,  5  0
binde = $mainMod+Shift, Left, resizeactive,  -5  0
binde = $mainMod+Shift, Up, resizeactive,     0 -5
binde = $mainMod+Shift, Down, resizeactive,   0  5


# Move active window around current workspace with mainMod + SHIFT + CTRL [←→↑↓]
$moveactivewindow=grep -q "true" <<< $(hyprctl activewindow -j | jq -r .floating) && hyprctl dispatch moveactive
binded = $mainMod+Shift+Ctrl, h, Move activewindow left, exec, $moveactivewindow -5 0 || hyprctl dispatch movewindow l
binded = $mainMod+Shift+Ctrl, l, Move activewindow right, exec, $moveactivewindow 5 0 || hyprctl dispatch movewindow r
binded = $mainMod+Shift+Ctrl, k, Move activewindow up, exec, $moveactivewindow  0 -5 || hyprctl dispatch movewindow u
binded = $mainMod+Shift+Ctrl, j, Move activewindow down, exec, $moveactivewindow 0 5 || hyprctl dispatch movewindow d

# Move/Resize focused window
bindm = $mainMod, Z, movewindow
bindm = $mainMod, X, resizewindow
